// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Person struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	PbData    []byte         `json:"pbData"`
	CreatedAt time.Time      `json:"createdAt"`
}
